# Grundkonfiguration för Jekyll och Just the Docs
title: Gemensamma designmönster
description: Designmönster med god tillgänglighet för svenska myndigheter

# VIKTIGT: Använd remote_theme istället för theme
remote_theme: just-the-docs/just-the-docs@v0.8.2

url: https://pattespatte.github.io
baseurl: /designmonster-demo

# LÄGG TILL DESSA RADER FÖR ATT FIXA SÖKVÄGAR
logo: false
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_level: 2

# Color scheme
color_scheme: light

# Aux links
aux_links:
  "GitHub":
    - "//github.com/pattespatte/designmonster-demo"

aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2024 Gemensamma designmönster."

# Collections
collections:
  docs:
    output: false

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag